import { Component, OnInit, ViewChild, OnDestroy } from "@angular/core";
import { FormBuilder, Validators, FormGroup } from "@angular/forms";
import { ServiceProvider } from "../../../config/services";
import { MESSAGES } from "../../../config/messages";
import { WEBSERVICE } from "../../../config/webservices";
import { AuthenticationService } from '../../../config/authentication.service';
import { MatTableDataSource } from '@angular/material/table';
import { MatPaginator } from '@angular/material/paginator';
import { MatSort } from '@angular/material/sort';
import { JwtHelperService } from '@auth0/angular-jwt';
import { trigger, state, style, transition, animate } from '@angular/animations';


@Component({
  selector: "listado-reglas-difusion",
  templateUrl: "listadoReglasDifusion.component.html",
  animations: [
    trigger('detailExpand', [
      state('collapsed', style({ height: '0px', minHeight: '0' })),
      state('expanded', style({ height: '*' })),
      transition('expanded <=> collapsed', animate('225ms cubic-bezier(0.4, 0.0, 0.2, 1)')),
    ]),
  ],
})

export class ListadoReglasDifusionComponent implements OnInit {
  columnasListadoReglas: string[] = ["SEGMENTO", "CLASE_SERVICIO", "HORA_INICIO", "TIPO_DIA", "MUNICIPIO", "MINUTOS", "ESTADO", "ACCION"];
  @ViewChild(MatPaginator, { static: true }) paginator: MatPaginator;
  @ViewChild(MatSort, { static: true }) sort: MatSort;
  dataSource: MatTableDataSource<any>;


  constructor(
    private authenticationService: AuthenticationService,
    private fb: FormBuilder,
    public ServiceProvider: ServiceProvider,
    public jwtHelper: JwtHelperService
  ) { }

  ngOnInit() {
    this.ServiceProvider.setTituloPestana("Reglas de difusión");
    this.getListadoReglas();

  }

  async getListadoReglas() {
    try {
      // const listado: any = await this.ServiceProvider.get(WEBSERVICE.GET_LISTADO_ENVIOS_DOD);
      const listadoReglas: any = this.reglasDifusion;


      this.dataSource = new MatTableDataSource(listadoReglas);
      this.dataSource.paginator = this.paginator;
      this.dataSource.sort = this.sort;

    } catch (error) {
      // this.ServiceProvider.openPopup("error", error);
      console.error(error);
    } finally {
      this.ServiceProvider.preloaderOff();
    }
  }

  eliminarComa(str) {
    return str.replace(/(^\s*,)|(,\s*$)/g, '');
  }


  reglasDifusion: any[] = [
    {
      "_id": {
        "$oid": "5f3fd1a20ce22b44f0b90399"
      },
      "REGLA": "1",
      "SEGMENTO": [
        "Hogares"
      ],
      "CLASE_SERVICIO": [
        "Oxigenodependientes"
      ],
      "TIPO_HORARIO": "Diurno",
      "HORA_INICIO": "7:00:00",
      "HORA_FIN": "19:00:00",
      "TIPO_DIA": [
        "Lunes",
        "Martes",
        "Miercoles",
        "Jueves",
        "Viernes",
        "Sabado"
      ],
      "MUNICIPIO": [
        "MANIZALES",
        "DOSQUEBRADAS",
        "LA VIRGINIA",
        "CHINCHINA",
        "PALESTINA",
        "VILLAMARIA",
        "MARSELLA",
        "SANTA ROSA",
        "RISARALDA",
        "ANSERMA",
        "VITERBO",
        "BELEN DE UMBRIA",
        "NEIRA",
        "MARMATO",
        "PACORA",
        "SUPIA",
        "VICTORIA",
        "NORCASIA",
        "LA DORADA",
        "TAMESIS",
        "JARDIN",
        "ANDES",
        "ABEJORRAL",
        "SANTA BARBARA",
        "LA PINTADA",
        "VALPARAISO",
        "CARAMANTA",
        "NARIÑO",
        "ARGELIA",
        "SONSON",
        "MARULANDA",
        "PENSILVANIA",
        "SAMANA",
        "SALAMINA",
        "AGUADAS",
        "ARANZAZU",
        "QUINCHIA",
        "SAN JOSE",
        "BELALCAZAR",
        "APIA",
        "SANTUARIO",
        "MISTRATO",
        "FILADELFIA",
        "LA MERCED",
        "RIOSUCIO",
        "GUATICA",
        "MARQUETALIA",
        "MANZANARES",
        "BALBOA",
        "LA CELIA",
        "PUEBLO RICO",
        "PEREIRA"
      ],
      "ESTADO": true,
      "MINUTOS": 5
    }, {
      "_id": {
        "$oid": "5f3fd1a20ce22b44f0b9039a"
      },
      "REGLA": "2",
      "SEGMENTO": [
        "Hogares"
      ],
      "CLASE_SERVICIO": [
        "Oxigenodependientes"
      ],
      "TIPO_HORARIO": "Diurno",
      "HORA_INICIO": "7:00:00",
      "HORA_FIN": "19:00:00",
      "TIPO_DIA": [
        "Domingo",
        "Festivo"
      ],
      "MUNICIPIO": [
        "MANIZALES",
        "DOSQUEBRADAS",
        "LA VIRGINIA",
        "CHINCHINA",
        "PALESTINA",
        "VILLAMARIA",
        "MARSELLA",
        "SANTA ROSA",
        "RISARALDA",
        "ANSERMA",
        "VITERBO",
        "BELEN DE UMBRIA",
        "NEIRA",
        "MARMATO",
        "PACORA",
        "SUPIA",
        "VICTORIA",
        "NORCASIA",
        "LA DORADA",
        "TAMESIS",
        "JARDIN",
        "ANDES",
        "ABEJORRAL",
        "SANTA BARBARA",
        "LA PINTADA",
        "VALPARAISO",
        "CARAMANTA",
        "NARIÑO",
        "ARGELIA",
        "SONSON",
        "MARULANDA",
        "PENSILVANIA",
        "SAMANA",
        "SALAMINA",
        "AGUADAS",
        "ARANZAZU",
        "QUINCHIA",
        "SAN JOSE",
        "BELALCAZAR",
        "APIA",
        "SANTUARIO",
        "MISTRATO",
        "FILADELFIA",
        "LA MERCED",
        "RIOSUCIO",
        "GUATICA",
        "MARQUETALIA",
        "MANZANARES",
        "BALBOA",
        "LA CELIA",
        "PUEBLO RICO",
        "PEREIRA"
      ],
      "ESTADO": true,
      "MINUTOS": 5
    }, {
      "_id": {
        "$oid": "5f3fd1a20ce22b44f0b9039b"
      },
      "REGLA": "3",
      "SEGMENTO": [
        "Hogares"
      ],
      "CLASE_SERVICIO": [
        "Residencial",
        "Areas comunes",
        "Comercial",
        "Provisional",
        "Industrial",
        "Especial Educativo",
        "Especial Asistencial"
      ],
      "TIPO_HORARIO": "Diurno",
      "HORA_INICIO": "5:00:00",
      "HORA_FIN": "22:00:00",
      "TIPO_DIA": [
        "Lunes",
        "Martes",
        "Miercoles",
        "Jueves",
        "Viernes",
        "Sabado"
      ],
      "MUNICIPIO": [
        "MANIZALES",
        "DOSQUEBRADAS",
        "LA VIRGINIA",
        "CHINCHINA",
        "PALESTINA",
        "VILLAMARIA",
        "MARSELLA",
        "SANTA ROSA",
        "RISARALDA",
        "ANSERMA",
        "VITERBO",
        "BELEN DE UMBRIA",
        "NEIRA",
        "MARMATO",
        "PACORA",
        "SUPIA",
        "VICTORIA",
        "NORCASIA",
        "LA DORADA",
        "TAMESIS",
        "JARDIN",
        "ANDES",
        "ABEJORRAL",
        "SANTA BARBARA",
        "LA PINTADA",
        "VALPARAISO",
        "CARAMANTA",
        "NARIÑO",
        "ARGELIA",
        "SONSON",
        "MARULANDA",
        "PENSILVANIA",
        "SAMANA",
        "SALAMINA",
        "AGUADAS",
        "ARANZAZU",
        "QUINCHIA",
        "SAN JOSE",
        "BELALCAZAR",
        "APIA",
        "SANTUARIO",
        "MISTRATO",
        "FILADELFIA",
        "LA MERCED",
        "RIOSUCIO",
        "GUATICA",
        "MARQUETALIA",
        "MANZANARES",
        "BALBOA",
        "LA CELIA",
        "PUEBLO RICO",
        "PEREIRA"
      ],
      "ESTADO": false,
      "MINUTOS": 10
    }, {
      "_id": {
        "$oid": "5f3fd1a20ce22b44f0b9039c"
      },
      "REGLA": "4",
      "SEGMENTO": [
        "Hogares"
      ],
      "CLASE_SERVICIO": [
        "Residencial",
        "Areas comunes",
        "Comercial",
        "Provisional",
        "Industrial",
        "Especial Educativo",
        "Especial Asistencial"
      ],
      "TIPO_HORARIO": "Diurno",
      "HORA_INICIO": "5:00:00",
      "HORA_FIN": "22:00:00",
      "TIPO_DIA": [
        "Lunes",
        "Martes",
        "Miercoles",
        "Jueves",
        "Viernes",
        "Sabado"
      ],
      "MUNICIPIO": [
        "MANIZALES",
        "DOSQUEBRADAS"
      ],
      "ESTADO": true,
      "MINUTOS": 5
    }, {
      "_id": {
        "$oid": "5f3fd1a20ce22b44f0b9039d"
      },
      "REGLA": "5",
      "SEGMENTO": [
        "Hogares"
      ],
      "CLASE_SERVICIO": [
        "Residencial",
        "Areas comunes",
        "Comercial",
        "Provisional",
        "Industrial",
        "Especial Educativo",
        "Especial Asistencial"
      ],
      "TIPO_HORARIO": "Diurno",
      "HORA_INICIO": "5:00:00",
      "HORA_FIN": "18:00:00",
      "TIPO_DIA": [
        "Lunes",
        "Martes",
        "Miercoles",
        "Jueves",
        "Viernes",
        "Sabado"
      ],
      "MUNICIPIO": [
        "LA VIRGINIA",
        "CHINCHINA",
        "PALESTINA",
        "VILLAMARIA",
        "MARSELLA",
        "SANTA ROSA",
        "RISARALDA",
        "ANSERMA",
        "VITERBO",
        "BELEN DE UMBRIA",
        "NEIRA",
        "MARMATO",
        "PACORA",
        "SUPIA",
        "VICTORIA",
        "NORCASIA",
        "LA DORADA",
        "TAMESIS",
        "JARDIN",
        "ANDES",
        "ABEJORRAL",
        "SANTA BARBARA",
        "LA PINTADA",
        "VALPARAISO",
        "CARAMANTA",
        "NARIÑO",
        "ARGELIA",
        "SONSON",
        "MARULANDA",
        "PENSILVANIA",
        "SAMANA",
        "SALAMINA",
        "AGUADAS",
        "ARANZAZU",
        "QUINCHIA",
        "SAN JOSE",
        "BELALCAZAR",
        "APIA",
        "SANTUARIO",
        "MISTRATO",
        "FILADELFIA",
        "LA MERCED",
        "RIOSUCIO",
        "GUATICA",
        "MARQUETALIA",
        "MANZANARES",
        "BALBOA",
        "LA CELIA",
        "PUEBLO RICO",
        "PEREIRA"
      ],
      "ESTADO": false,
      "MINUTOS": 15
    }, {
      "_id": {
        "$oid": "5f3fd1a20ce22b44f0b9039e"
      },
      "REGLA": "6",
      "SEGMENTO": [
        "Hogares"
      ],
      "CLASE_SERVICIO": [
        "Residencial",
        "Areas comunes",
        "Comercial",
        "Provisional",
        "Industrial",
        "Especial Educativo",
        "Especial Asistencial"
      ],
      "TIPO_HORARIO": "Diurno",
      "HORA_INICIO": "7:00:00",
      "HORA_FIN": "22:00:00",
      "TIPO_DIA": [
        "Domingo",
        "Festivo"
      ],
      "MUNICIPIO": [
        "MANIZALES",
        "DOSQUEBRADAS",
        "LA VIRGINIA",
        "CHINCHINA",
        "PALESTINA",
        "VILLAMARIA",
        "MARSELLA",
        "SANTA ROSA",
        "RISARALDA",
        "ANSERMA",
        "VITERBO",
        "BELEN DE UMBRIA",
        "NEIRA",
        "MARMATO",
        "PACORA",
        "SUPIA",
        "VICTORIA",
        "NORCASIA",
        "LA DORADA",
        "TAMESIS",
        "JARDIN",
        "ANDES",
        "ABEJORRAL",
        "SANTA BARBARA",
        "LA PINTADA",
        "VALPARAISO",
        "CARAMANTA",
        "NARIÑO",
        "ARGELIA",
        "SONSON",
        "MARULANDA",
        "PENSILVANIA",
        "SAMANA",
        "SALAMINA",
        "AGUADAS",
        "ARANZAZU",
        "QUINCHIA",
        "SAN JOSE",
        "BELALCAZAR",
        "APIA",
        "SANTUARIO",
        "MISTRATO",
        "FILADELFIA",
        "LA MERCED",
        "RIOSUCIO",
        "GUATICA",
        "MARQUETALIA",
        "MANZANARES",
        "BALBOA",
        "LA CELIA",
        "PUEBLO RICO",
        "PEREIRA"
      ],
      "ESTADO": true,
      "MINUTOS": 10
    }, {
      "_id": {
        "$oid": "5f3fd1a20ce22b44f0b9039f"
      },
      "REGLA": "7",
      "SEGMENTO": [
        "Hogares"
      ],
      "CLASE_SERVICIO": [
        "Residencial",
        "Areas comunes",
        "Comercial",
        "Provisional",
        "Industrial",
        "Especial Educativo",
        "Especial Asistencial"
      ],
      "TIPO_HORARIO": "Diurno",
      "HORA_INICIO": "8:00:00",
      "HORA_FIN": "17:00:00",
      "TIPO_DIA": [
        "Domingo",
        "Festivo"
      ],
      "MUNICIPIO": [
        "LA VIRGINIA",
        "CHINCHINA",
        "PALESTINA",
        "VILLAMARIA",
        "MARSELLA",
        "SANTA ROSA",
        "RISARALDA",
        "ANSERMA",
        "VITERBO",
        "BELEN DE UMBRIA",
        "NEIRA",
        "MARMATO",
        "PACORA",
        "SUPIA",
        "VICTORIA",
        "NORCASIA",
        "LA DORADA",
        "TAMESIS",
        "JARDIN",
        "ANDES",
        "ABEJORRAL",
        "SANTA BARBARA",
        "LA PINTADA",
        "VALPARAISO",
        "CARAMANTA",
        "NARIÑO",
        "ARGELIA",
        "SONSON",
        "MARULANDA",
        "PENSILVANIA",
        "SAMANA",
        "SALAMINA",
        "AGUADAS",
        "ARANZAZU",
        "QUINCHIA",
        "SAN JOSE",
        "BELALCAZAR",
        "APIA",
        "SANTUARIO",
        "MISTRATO",
        "FILADELFIA",
        "LA MERCED",
        "RIOSUCIO",
        "GUATICA",
        "MARQUETALIA",
        "MANZANARES",
        "BALBOA",
        "LA CELIA",
        "PUEBLO RICO",
        "PEREIRA"
      ],
      "ESTADO": true,
      "MINUTOS": 15
    }, {
      "_id": {
        "$oid": "5f3fd1a20ce22b44f0b903a0"
      },
      "REGLA": "8",
      "SEGMENTO": [
        "Hogares"
      ],
      "CLASE_SERVICIO": [
        "Residencial",
        "Areas comunes",
        "Comercial",
        "Provisional",
        "Industrial",
        "Especial Educativo",
        "Especial Asistencial"
      ],
      "TIPO_HORARIO": "Diurno",
      "HORA_INICIO": "7:00:00",
      "HORA_FIN": "22:00:00",
      "TIPO_DIA": [
        "Domingo",
        "Festivo"
      ],
      "MUNICIPIO": [
        "MANIZALES",
        "DOSQUEBRADAS"
      ],
      "ESTADO": true,
      "MINUTOS": 5
    }, {
      "_id": {
        "$oid": "5f3fd1a20ce22b44f0b903a1"
      },
      "REGLA": "9",
      "SEGMENTO": [
        "Hogares"
      ],
      "CLASE_SERVICIO": [
        "Oxigenodependientes"
      ],
      "TIPO_HORARIO": "Nocturno",
      "HORA_INICIO": "19:00:00",
      "HORA_FIN": "7:00:00",
      "TIPO_DIA": [
        "Lunes",
        "Martes",
        "Miercoles",
        "Jueves",
        "Viernes",
        "Sabado",
        "Domingo",
        "Festivo"
      ],
      "MUNICIPIO": [
        "MANIZALES",
        "DOSQUEBRADAS",
        "LA VIRGINIA",
        "CHINCHINA",
        "PALESTINA",
        "VILLAMARIA",
        "MARSELLA",
        "SANTA ROSA",
        "RISARALDA",
        "ANSERMA",
        "VITERBO",
        "BELEN DE UMBRIA",
        "NEIRA",
        "MARMATO",
        "PACORA",
        "SUPIA",
        "VICTORIA",
        "NORCASIA",
        "LA DORADA",
        "TAMESIS",
        "JARDIN",
        "ANDES",
        "ABEJORRAL",
        "SANTA BARBARA",
        "LA PINTADA",
        "VALPARAISO",
        "CARAMANTA",
        "NARIÑO",
        "ARGELIA",
        "SONSON",
        "MARULANDA",
        "PENSILVANIA",
        "SAMANA",
        "SALAMINA",
        "AGUADAS",
        "ARANZAZU",
        "QUINCHIA",
        "SAN JOSE",
        "BELALCAZAR",
        "APIA",
        "SANTUARIO",
        "MISTRATO",
        "FILADELFIA",
        "LA MERCED",
        "RIOSUCIO",
        "GUATICA",
        "MARQUETALIA",
        "MANZANARES",
        "BALBOA",
        "LA CELIA",
        "PUEBLO RICO",
        "PEREIRA"
      ],
      "ESTADO": true,
      "MINUTOS": 5
    }, {
      "_id": {
        "$oid": "5f3fd1a20ce22b44f0b903a2"
      },
      "REGLA": "10",
      "SEGMENTO": [
        "Hogares"
      ],
      "CLASE_SERVICIO": [
        "Residencial",
        "Areas comunes",
        "Comercial",
        "Provisional",
        "Industrial",
        "Especial Educativo",
        "Oxigenodependientes"
      ],
      "TIPO_HORARIO": "Diurno",
      "HORA_INICIO": "5:00:00",
      "HORA_FIN": "22:00:00",
      "TIPO_DIA": [
        "Lunes",
        "Martes",
        "Miercoles",
        "Jueves",
        "Viernes",
        "Sabado"
      ],
      "MUNICIPIO": [
        "MANIZALES",
        "DOSQUEBRADAS",
        "LA VIRGINIA",
        "CHINCHINA",
        "PALESTINA",
        "VILLAMARIA",
        "MARSELLA",
        "SANTA ROSA",
        "RISARALDA",
        "ANSERMA",
        "VITERBO",
        "BELEN DE UMBRIA",
        "NEIRA",
        "MARMATO",
        "PACORA",
        "SUPIA",
        "VICTORIA",
        "NORCASIA",
        "LA DORADA",
        "TAMESIS",
        "JARDIN",
        "ANDES",
        "ABEJORRAL",
        "SANTA BARBARA",
        "LA PINTADA",
        "VALPARAISO",
        "CARAMANTA",
        "NARIÑO",
        "ARGELIA",
        "SONSON",
        "MARULANDA",
        "PENSILVANIA",
        "SAMANA",
        "SALAMINA",
        "AGUADAS",
        "ARANZAZU",
        "QUINCHIA",
        "SAN JOSE",
        "BELALCAZAR",
        "APIA",
        "SANTUARIO",
        "MISTRATO",
        "FILADELFIA",
        "LA MERCED",
        "RIOSUCIO",
        "GUATICA",
        "MARQUETALIA",
        "MANZANARES",
        "BALBOA",
        "LA CELIA",
        "PUEBLO RICO",
        "PEREIRA"
      ],
      "ESTADO": false,
      "MINUTOS": 10
    }, {
      "_id": {
        "$oid": "5f3fd1a20ce22b44f0b903a3"
      },
      "REGLA": "11",
      "SEGMENTO": [
        "Hogares"
      ],
      "CLASE_SERVICIO": [
        "Residencial",
        "Areas comunes",
        "Comercial",
        "Provisional",
        "Industrial",
        "Especial Educativo",
        "Oxigenodependientes"
      ],
      "TIPO_HORARIO": "Diurno",
      "HORA_INICIO": "7:00:00",
      "HORA_FIN": "22:00:00",
      "TIPO_DIA": [
        "Domingo",
        "Festivo"
      ],
      "MUNICIPIO": [
        "MANIZALES",
        "DOSQUEBRADAS",
        "LA VIRGINIA",
        "CHINCHINA",
        "PALESTINA",
        "VILLAMARIA",
        "MARSELLA",
        "SANTA ROSA",
        "RISARALDA",
        "ANSERMA",
        "VITERBO",
        "BELEN DE UMBRIA",
        "NEIRA",
        "MARMATO",
        "PACORA",
        "SUPIA",
        "VICTORIA",
        "NORCASIA",
        "LA DORADA",
        "TAMESIS",
        "JARDIN",
        "ANDES",
        "ABEJORRAL",
        "SANTA BARBARA",
        "LA PINTADA",
        "VALPARAISO",
        "CARAMANTA",
        "NARIÑO",
        "ARGELIA",
        "SONSON",
        "MARULANDA",
        "PENSILVANIA",
        "SAMANA",
        "SALAMINA",
        "AGUADAS",
        "ARANZAZU",
        "QUINCHIA",
        "SAN JOSE",
        "BELALCAZAR",
        "APIA",
        "SANTUARIO",
        "MISTRATO",
        "FILADELFIA",
        "LA MERCED",
        "RIOSUCIO",
        "GUATICA",
        "MARQUETALIA",
        "MANZANARES",
        "BALBOA",
        "LA CELIA",
        "PUEBLO RICO",
        "PEREIRA"
      ],
      "ESTADO": false,
      "MINUTOS": 10
    }, {
      "_id": {
        "$oid": "5f3fd1a20ce22b44f0b903a4"
      },
      "REGLA": "12",
      "SEGMENTO": [
        "Empresas"
      ],
      "CLASE_SERVICIO": [
        "Residencial",
        "Areas comunes",
        "Comercial",
        "Provisional",
        "Industrial",
        "Especial Educativo",
        "Oxigenodependientes"
      ],
      "TIPO_HORARIO": "Diurno",
      "HORA_INICIO": "7:00:00",
      "HORA_FIN": "22:00:00",
      "TIPO_DIA": [
        "Lunes",
        "Martes",
        "Miercoles",
        "Jueves",
        "Viernes",
        "Sabado"
      ],
      "MUNICIPIO": [
        "MANIZALES",
        "DOSQUEBRADAS",
        "LA VIRGINIA",
        "CHINCHINA",
        "PALESTINA",
        "VILLAMARIA",
        "MARSELLA",
        "SANTA ROSA",
        "RISARALDA",
        "ANSERMA",
        "VITERBO",
        "BELEN DE UMBRIA",
        "NEIRA",
        "MARMATO",
        "PACORA",
        "SUPIA",
        "VICTORIA",
        "NORCASIA",
        "LA DORADA",
        "TAMESIS",
        "JARDIN",
        "ANDES",
        "ABEJORRAL",
        "SANTA BARBARA",
        "LA PINTADA",
        "VALPARAISO",
        "CARAMANTA",
        "NARIÑO",
        "ARGELIA",
        "SONSON",
        "MARULANDA",
        "PENSILVANIA",
        "SAMANA",
        "SALAMINA",
        "AGUADAS",
        "ARANZAZU",
        "QUINCHIA",
        "SAN JOSE",
        "BELALCAZAR",
        "APIA",
        "SANTUARIO",
        "MISTRATO",
        "FILADELFIA",
        "LA MERCED",
        "RIOSUCIO",
        "GUATICA",
        "MARQUETALIA",
        "MANZANARES",
        "BALBOA",
        "LA CELIA",
        "PUEBLO RICO",
        "PEREIRA"
      ],
      "ESTADO": false,
      "MINUTOS": 10
    }, {
      "_id": {
        "$oid": "5f3fd1a20ce22b44f0b903a5"
      },
      "REGLA": "13",
      "SEGMENTO": [
        "Empresas"
      ],
      "CLASE_SERVICIO": [
        "Especial Asistencial"
      ],
      "TIPO_HORARIO": "Diurno",
      "HORA_INICIO": "7:00:00",
      "HORA_FIN": "19:00:00",
      "TIPO_DIA": [
        "Domingo",
        "Festivo"
      ],
      "MUNICIPIO": [
        "MANIZALES",
        "DOSQUEBRADAS",
        "LA VIRGINIA",
        "CHINCHINA",
        "PALESTINA",
        "VILLAMARIA",
        "MARSELLA",
        "SANTA ROSA",
        "RISARALDA",
        "ANSERMA",
        "VITERBO",
        "BELEN DE UMBRIA",
        "NEIRA",
        "MARMATO",
        "PACORA",
        "SUPIA",
        "VICTORIA",
        "NORCASIA",
        "LA DORADA",
        "TAMESIS",
        "JARDIN",
        "ANDES",
        "ABEJORRAL",
        "SANTA BARBARA",
        "LA PINTADA",
        "VALPARAISO",
        "CARAMANTA",
        "NARIÑO",
        "ARGELIA",
        "SONSON",
        "MARULANDA",
        "PENSILVANIA",
        "SAMANA",
        "SALAMINA",
        "AGUADAS",
        "ARANZAZU",
        "QUINCHIA",
        "SAN JOSE",
        "BELALCAZAR",
        "APIA",
        "SANTUARIO",
        "MISTRATO",
        "FILADELFIA",
        "LA MERCED",
        "RIOSUCIO",
        "GUATICA",
        "MARQUETALIA",
        "MANZANARES",
        "BALBOA",
        "LA CELIA",
        "PUEBLO RICO",
        "PEREIRA"
      ],
      "ESTADO": false,
      "MINUTOS": 5
    }, {
      "_id": {
        "$oid": "5f3fd1a20ce22b44f0b903a6"
      },
      "REGLA": "14",
      "SEGMENTO": [
        "Empresas"
      ],
      "CLASE_SERVICIO": [
        "Residencial",
        "Areas comunes",
        "Comercial",
        "Provisional",
        "Industrial",
        "Especial Educativo",
        "Oxigenodependientes",
        "Especial Asistencial"
      ],
      "TIPO_HORARIO": "Diurno",
      "HORA_INICIO": "00:00:00",
      "HORA_FIN": "23:59:59",
      "TIPO_DIA": [
        "Lunes",
        "Martes",
        "Miercoles",
        "Jueves",
        "Viernes",
        "Sabado",
        "Domingo",
        "Festivo"
      ],
      "MUNICIPIO": [
        "MARMATO"
      ],
      "ESTADO": false,
      "MINUTOS": 10
    }, {
      "_id": {
        "$oid": "5f3fd1a20ce22b44f0b903a7"
      },
      "REGLA": "15",
      "SEGMENTO": [
        "Empresas"
      ],
      "CLASE_SERVICIO": [
        "Especial Asistencial"
      ],
      "TIPO_HORARIO": "Diurno",
      "HORA_INICIO": "7:00:00",
      "HORA_FIN": "19:00:00",
      "TIPO_DIA": [
        "Lunes",
        "Martes",
        "Miercoles",
        "Jueves",
        "Viernes",
        "Sabado"
      ],
      "MUNICIPIO": [
        "MANIZALES",
        "DOSQUEBRADAS",
        "LA VIRGINIA",
        "CHINCHINA",
        "PALESTINA",
        "VILLAMARIA",
        "MARSELLA",
        "SANTA ROSA",
        "RISARALDA",
        "ANSERMA",
        "VITERBO",
        "BELEN DE UMBRIA",
        "NEIRA",
        "MARMATO",
        "PACORA",
        "SUPIA",
        "VICTORIA",
        "NORCASIA",
        "LA DORADA",
        "TAMESIS",
        "JARDIN",
        "ANDES",
        "ABEJORRAL",
        "SANTA BARBARA",
        "LA PINTADA",
        "VALPARAISO",
        "CARAMANTA",
        "NARIÑO",
        "ARGELIA",
        "SONSON",
        "MARULANDA",
        "PENSILVANIA",
        "SAMANA",
        "SALAMINA",
        "AGUADAS",
        "ARANZAZU",
        "QUINCHIA",
        "SAN JOSE",
        "BELALCAZAR",
        "APIA",
        "SANTUARIO",
        "MISTRATO",
        "FILADELFIA",
        "LA MERCED",
        "RIOSUCIO",
        "GUATICA",
        "MARQUETALIA",
        "MANZANARES",
        "BALBOA",
        "LA CELIA",
        "PUEBLO RICO",
        "PEREIRA"
      ],
      "ESTADO": false,
      "MINUTOS": 5
    }, {
      "_id": {
        "$oid": "5f3fd1a20ce22b44f0b903a8"
      },
      "REGLA": "16",
      "SEGMENTO": [
        "Empresas",
        "Gobierno"
      ],
      "CLASE_SERVICIO": [
        "Residencial",
        "Areas comunes",
        "Comercial",
        "Provisional",
        "Industrial",
        "Especial Educativo",
        "Oxigenodependientes"
      ],
      "TIPO_HORARIO": "Diurno",
      "HORA_INICIO": "9:00:00",
      "HORA_FIN": "22:00:00",
      "TIPO_DIA": [
        "Domingo",
        "Festivo"
      ],
      "MUNICIPIO": [
        "MANIZALES",
        "DOSQUEBRADAS",
        "LA VIRGINIA",
        "CHINCHINA",
        "PALESTINA",
        "VILLAMARIA",
        "MARSELLA",
        "SANTA ROSA",
        "RISARALDA",
        "ANSERMA",
        "VITERBO",
        "BELEN DE UMBRIA",
        "NEIRA",
        "MARMATO",
        "PACORA",
        "SUPIA",
        "VICTORIA",
        "NORCASIA",
        "LA DORADA",
        "TAMESIS",
        "JARDIN",
        "ANDES",
        "ABEJORRAL",
        "SANTA BARBARA",
        "LA PINTADA",
        "VALPARAISO",
        "CARAMANTA",
        "NARIÑO",
        "ARGELIA",
        "SONSON",
        "MARULANDA",
        "PENSILVANIA",
        "SAMANA",
        "SALAMINA",
        "AGUADAS",
        "ARANZAZU",
        "QUINCHIA",
        "SAN JOSE",
        "BELALCAZAR",
        "APIA",
        "SANTUARIO",
        "MISTRATO",
        "FILADELFIA",
        "LA MERCED",
        "RIOSUCIO",
        "GUATICA",
        "MARQUETALIA",
        "MANZANARES",
        "BALBOA",
        "LA CELIA",
        "PUEBLO RICO",
        "PEREIRA"
      ],
      "ESTADO": false,
      "MINUTOS": 10
    }, {
      "_id": {
        "$oid": "5f3fd1a20ce22b44f0b903a9"
      },
      "REGLA": "17",
      "SEGMENTO": [
        "Empresas",
        "Gobierno",
        "Grandes Clientes"
      ],
      "CLASE_SERVICIO": [
        "Especial Asistencial"
      ],
      "TIPO_HORARIO": "Nocturno",
      "HORA_INICIO": "19:00:00",
      "HORA_FIN": "7:00:00",
      "TIPO_DIA": [
        "Lunes",
        "Martes",
        "Miercoles",
        "Jueves",
        "Viernes",
        "Sabado",
        "Domingo",
        "Festivo"
      ],
      "MUNICIPIO": [
        "MANIZALES",
        "DOSQUEBRADAS",
        "LA VIRGINIA",
        "CHINCHINA",
        "PALESTINA",
        "VILLAMARIA",
        "MARSELLA",
        "SANTA ROSA",
        "RISARALDA",
        "ANSERMA",
        "VITERBO",
        "BELEN DE UMBRIA",
        "NEIRA",
        "MARMATO",
        "PACORA",
        "SUPIA",
        "VICTORIA",
        "NORCASIA",
        "LA DORADA",
        "TAMESIS",
        "JARDIN",
        "ANDES",
        "ABEJORRAL",
        "SANTA BARBARA",
        "LA PINTADA",
        "VALPARAISO",
        "CARAMANTA",
        "NARIÑO",
        "ARGELIA",
        "SONSON",
        "MARULANDA",
        "PENSILVANIA",
        "SAMANA",
        "SALAMINA",
        "AGUADAS",
        "ARANZAZU",
        "QUINCHIA",
        "SAN JOSE",
        "BELALCAZAR",
        "APIA",
        "SANTUARIO",
        "MISTRATO",
        "FILADELFIA",
        "LA MERCED",
        "RIOSUCIO",
        "GUATICA",
        "MARQUETALIA",
        "MANZANARES",
        "BALBOA",
        "LA CELIA",
        "PUEBLO RICO",
        "PEREIRA"
      ],
      "ESTADO": false,
      "MINUTOS": 5
    }, {
      "_id": {
        "$oid": "5f3fd1a20ce22b44f0b903aa"
      },
      "REGLA": "18",
      "SEGMENTO": [
        "Gobierno"
      ],
      "CLASE_SERVICIO": [
        "Especial Asistencial"
      ],
      "TIPO_HORARIO": "Diurno",
      "HORA_INICIO": "7:00:00",
      "HORA_FIN": "19:00:00",
      "TIPO_DIA": [
        "Lunes",
        "Martes",
        "Miercoles",
        "Jueves",
        "Viernes",
        "Sabado"
      ],
      "MUNICIPIO": [
        "MANIZALES",
        "DOSQUEBRADAS",
        "LA VIRGINIA",
        "CHINCHINA",
        "PALESTINA",
        "VILLAMARIA",
        "MARSELLA",
        "SANTA ROSA",
        "RISARALDA",
        "ANSERMA",
        "VITERBO",
        "BELEN DE UMBRIA",
        "NEIRA",
        "MARMATO",
        "PACORA",
        "SUPIA",
        "VICTORIA",
        "NORCASIA",
        "LA DORADA",
        "TAMESIS",
        "JARDIN",
        "ANDES",
        "ABEJORRAL",
        "SANTA BARBARA",
        "LA PINTADA",
        "VALPARAISO",
        "CARAMANTA",
        "NARIÑO",
        "ARGELIA",
        "SONSON",
        "MARULANDA",
        "PENSILVANIA",
        "SAMANA",
        "SALAMINA",
        "AGUADAS",
        "ARANZAZU",
        "QUINCHIA",
        "SAN JOSE",
        "BELALCAZAR",
        "APIA",
        "SANTUARIO",
        "MISTRATO",
        "FILADELFIA",
        "LA MERCED",
        "RIOSUCIO",
        "GUATICA",
        "MARQUETALIA",
        "MANZANARES",
        "BALBOA",
        "LA CELIA",
        "PUEBLO RICO",
        "PEREIRA"
      ],
      "ESTADO": false,
      "MINUTOS": 5
    }, {
      "_id": {
        "$oid": "5f3fd1a20ce22b44f0b903ab"
      },
      "REGLA": "19",
      "SEGMENTO": [
        "Gobierno"
      ],
      "CLASE_SERVICIO": [
        "Especial Asistencial"
      ],
      "TIPO_HORARIO": "Diurno",
      "HORA_INICIO": "7:00:00",
      "HORA_FIN": "19:00:00",
      "TIPO_DIA": [
        "Domingo",
        "Festivo"
      ],
      "MUNICIPIO": [
        "MANIZALES",
        "DOSQUEBRADAS",
        "LA VIRGINIA",
        "CHINCHINA",
        "PALESTINA",
        "VILLAMARIA",
        "MARSELLA",
        "SANTA ROSA",
        "RISARALDA",
        "ANSERMA",
        "VITERBO",
        "BELEN DE UMBRIA",
        "NEIRA",
        "MARMATO",
        "PACORA",
        "SUPIA",
        "VICTORIA",
        "NORCASIA",
        "LA DORADA",
        "TAMESIS",
        "JARDIN",
        "ANDES",
        "ABEJORRAL",
        "SANTA BARBARA",
        "LA PINTADA",
        "VALPARAISO",
        "CARAMANTA",
        "NARIÑO",
        "ARGELIA",
        "SONSON",
        "MARULANDA",
        "PENSILVANIA",
        "SAMANA",
        "SALAMINA",
        "AGUADAS",
        "ARANZAZU",
        "QUINCHIA",
        "SAN JOSE",
        "BELALCAZAR",
        "APIA",
        "SANTUARIO",
        "MISTRATO",
        "FILADELFIA",
        "LA MERCED",
        "RIOSUCIO",
        "GUATICA",
        "MARQUETALIA",
        "MANZANARES",
        "BALBOA",
        "LA CELIA",
        "PUEBLO RICO",
        "PEREIRA"
      ],
      "ESTADO": false,
      "MINUTOS": 5
    }, {
      "_id": {
        "$oid": "5f3fd1a20ce22b44f0b903ac"
      },
      "REGLA": "20",
      "SEGMENTO": [
        "Gobierno",
        "Grandes Clientes"
      ],
      "CLASE_SERVICIO": [
        "Especial Asistencial"
      ],
      "TIPO_HORARIO": "Nocturno",
      "HORA_INICIO": "19:00:00",
      "HORA_FIN": "7:00:00",
      "TIPO_DIA": [
        "Lunes",
        "Martes",
        "Miercoles",
        "Jueves",
        "Viernes",
        "Sabado"
      ],
      "MUNICIPIO": [
        "MANIZALES",
        "DOSQUEBRADAS",
        "LA VIRGINIA",
        "CHINCHINA",
        "PALESTINA",
        "VILLAMARIA",
        "MARSELLA",
        "SANTA ROSA",
        "RISARALDA",
        "ANSERMA",
        "VITERBO",
        "BELEN DE UMBRIA",
        "NEIRA",
        "MARMATO",
        "PACORA",
        "SUPIA",
        "VICTORIA",
        "NORCASIA",
        "LA DORADA",
        "TAMESIS",
        "JARDIN",
        "ANDES",
        "ABEJORRAL",
        "SANTA BARBARA",
        "LA PINTADA",
        "VALPARAISO",
        "CARAMANTA",
        "NARIÑO",
        "ARGELIA",
        "SONSON",
        "MARULANDA",
        "PENSILVANIA",
        "SAMANA",
        "SALAMINA",
        "AGUADAS",
        "ARANZAZU",
        "QUINCHIA",
        "SAN JOSE",
        "BELALCAZAR",
        "APIA",
        "SANTUARIO",
        "MISTRATO",
        "FILADELFIA",
        "LA MERCED",
        "RIOSUCIO",
        "GUATICA",
        "MARQUETALIA",
        "MANZANARES",
        "BALBOA",
        "LA CELIA",
        "PUEBLO RICO",
        "PEREIRA"
      ],
      "ESTADO": false,
      "MINUTOS": 5
    }, {
      "_id": {
        "$oid": "5f3fd1a20ce22b44f0b903ad"
      },
      "REGLA": "21",
      "SEGMENTO": [
        "Gobierno"
      ],
      "CLASE_SERVICIO": [
        "Residencial",
        "Areas comunes",
        "Comercial",
        "Provisional",
        "Industrial",
        "Especial Educativo",
        "Oxigenodependientes"
      ],
      "TIPO_HORARIO": "Diurno",
      "HORA_INICIO": "7:00:00",
      "HORA_FIN": "22:00:00",
      "TIPO_DIA": [
        "Lunes",
        "Martes",
        "Miercoles",
        "Jueves",
        "Viernes",
        "Sabado"
      ],
      "MUNICIPIO": [
        "MANIZALES",
        "DOSQUEBRADAS",
        "LA VIRGINIA",
        "CHINCHINA",
        "PALESTINA",
        "VILLAMARIA",
        "MARSELLA",
        "SANTA ROSA",
        "RISARALDA",
        "ANSERMA",
        "VITERBO",
        "BELEN DE UMBRIA",
        "NEIRA",
        "MARMATO",
        "PACORA",
        "SUPIA",
        "VICTORIA",
        "NORCASIA",
        "LA DORADA",
        "TAMESIS",
        "JARDIN",
        "ANDES",
        "ABEJORRAL",
        "SANTA BARBARA",
        "LA PINTADA",
        "VALPARAISO",
        "CARAMANTA",
        "NARIÑO",
        "ARGELIA",
        "SONSON",
        "MARULANDA",
        "PENSILVANIA",
        "SAMANA",
        "SALAMINA",
        "AGUADAS",
        "ARANZAZU",
        "QUINCHIA",
        "SAN JOSE",
        "BELALCAZAR",
        "APIA",
        "SANTUARIO",
        "MISTRATO",
        "FILADELFIA",
        "LA MERCED",
        "RIOSUCIO",
        "GUATICA",
        "MARQUETALIA",
        "MANZANARES",
        "BALBOA",
        "LA CELIA",
        "PUEBLO RICO",
        "PEREIRA"
      ],
      "ESTADO": true,
      "MINUTOS": 10
    }, {
      "_id": {
        "$oid": "5f3fd1a20ce22b44f0b903ae"
      },
      "REGLA": "22",
      "SEGMENTO": [
        "Grandes Clientes"
      ],
      "CLASE_SERVICIO": [
        "Especial Asistencial"
      ],
      "TIPO_HORARIO": "Diurno",
      "HORA_INICIO": "7:00:00",
      "HORA_FIN": "19:00:00",
      "TIPO_DIA": [
        "Lunes",
        "Martes",
        "Miercoles",
        "Jueves",
        "Viernes",
        "Sabado"
      ],
      "MUNICIPIO": [
        "MANIZALES",
        "DOSQUEBRADAS",
        "LA VIRGINIA",
        "CHINCHINA",
        "PALESTINA",
        "VILLAMARIA",
        "MARSELLA",
        "SANTA ROSA",
        "RISARALDA",
        "ANSERMA",
        "VITERBO",
        "BELEN DE UMBRIA",
        "NEIRA",
        "MARMATO",
        "PACORA",
        "SUPIA",
        "VICTORIA",
        "NORCASIA",
        "LA DORADA",
        "TAMESIS",
        "JARDIN",
        "ANDES",
        "ABEJORRAL",
        "SANTA BARBARA",
        "LA PINTADA",
        "VALPARAISO",
        "CARAMANTA",
        "NARIÑO",
        "ARGELIA",
        "SONSON",
        "MARULANDA",
        "PENSILVANIA",
        "SAMANA",
        "SALAMINA",
        "AGUADAS",
        "ARANZAZU",
        "QUINCHIA",
        "SAN JOSE",
        "BELALCAZAR",
        "APIA",
        "SANTUARIO",
        "MISTRATO",
        "FILADELFIA",
        "LA MERCED",
        "RIOSUCIO",
        "GUATICA",
        "MARQUETALIA",
        "MANZANARES",
        "BALBOA",
        "LA CELIA",
        "PUEBLO RICO",
        "PEREIRA"
      ],
      "ESTADO": true,
      "MINUTOS": 5
    }, {
      "_id": {
        "$oid": "5f3fd1a20ce22b44f0b903af"
      },
      "REGLA": "23",
      "SEGMENTO": [
        "Grandes Clientes"
      ],
      "CLASE_SERVICIO": [
        "Residencial",
        "Areas comunes",
        "Comercial",
        "Provisional",
        "Industrial",
        "Especial Educativo",
        "Oxigenodependientes"
      ],
      "TIPO_HORARIO": "Diurno",
      "HORA_INICIO": "7:00:00",
      "HORA_FIN": "19:00:00",
      "TIPO_DIA": [
        "Domingo",
        "Festivo"
      ],
      "MUNICIPIO": [
        "MANIZALES",
        "DOSQUEBRADAS",
        "LA VIRGINIA",
        "CHINCHINA",
        "PALESTINA",
        "VILLAMARIA",
        "MARSELLA",
        "SANTA ROSA",
        "RISARALDA",
        "ANSERMA",
        "VITERBO",
        "BELEN DE UMBRIA",
        "NEIRA",
        "MARMATO",
        "PACORA",
        "SUPIA",
        "VICTORIA",
        "NORCASIA",
        "LA DORADA",
        "TAMESIS",
        "JARDIN",
        "ANDES",
        "ABEJORRAL",
        "SANTA BARBARA",
        "LA PINTADA",
        "VALPARAISO",
        "CARAMANTA",
        "NARIÑO",
        "ARGELIA",
        "SONSON",
        "MARULANDA",
        "PENSILVANIA",
        "SAMANA",
        "SALAMINA",
        "AGUADAS",
        "ARANZAZU",
        "QUINCHIA",
        "SAN JOSE",
        "BELALCAZAR",
        "APIA",
        "SANTUARIO",
        "MISTRATO",
        "FILADELFIA",
        "LA MERCED",
        "RIOSUCIO",
        "GUATICA",
        "MARQUETALIA",
        "MANZANARES",
        "BALBOA",
        "LA CELIA",
        "PUEBLO RICO",
        "PEREIRA"
      ],
      "ESTADO": true,
      "MINUTOS": 10
    }, {
      "_id": {
        "$oid": "5f3fd1a20ce22b44f0b903b0"
      },
      "REGLA": "24",
      "SEGMENTO": [
        "Grandes Clientes"
      ],
      "CLASE_SERVICIO": [
        "Especial Asistencial"
      ],
      "TIPO_HORARIO": "Diurno",
      "HORA_INICIO": "7:00:00",
      "HORA_FIN": "19:00:00",
      "TIPO_DIA": [
        "Domingo",
        "Festivo"
      ],
      "MUNICIPIO": [
        "MANIZALES",
        "DOSQUEBRADAS",
        "LA VIRGINIA",
        "CHINCHINA",
        "PALESTINA",
        "VILLAMARIA",
        "MARSELLA",
        "SANTA ROSA",
        "RISARALDA",
        "ANSERMA",
        "VITERBO",
        "BELEN DE UMBRIA",
        "NEIRA",
        "MARMATO",
        "PACORA",
        "SUPIA",
        "VICTORIA",
        "NORCASIA",
        "LA DORADA",
        "TAMESIS",
        "JARDIN",
        "ANDES",
        "ABEJORRAL",
        "SANTA BARBARA",
        "LA PINTADA",
        "VALPARAISO",
        "CARAMANTA",
        "NARIÑO",
        "ARGELIA",
        "SONSON",
        "MARULANDA",
        "PENSILVANIA",
        "SAMANA",
        "SALAMINA",
        "AGUADAS",
        "ARANZAZU",
        "QUINCHIA",
        "SAN JOSE",
        "BELALCAZAR",
        "APIA",
        "SANTUARIO",
        "MISTRATO",
        "FILADELFIA",
        "LA MERCED",
        "RIOSUCIO",
        "GUATICA",
        "MARQUETALIA",
        "MANZANARES",
        "BALBOA",
        "LA CELIA",
        "PUEBLO RICO",
        "PEREIRA"
      ],
      "ESTADO": true,
      "MINUTOS": 5
    }, {
      "_id": {
        "$oid": "5f3fd1a20ce22b44f0b903b1"
      },
      "REGLA": "25",
      "SEGMENTO": [
        "Grandes Clientes"
      ],
      "CLASE_SERVICIO": [
        "Residencial",
        "Areas comunes",
        "Comercial",
        "Provisional",
        "Industrial",
        "Especial Educativo",
        "Oxigenodependientes"
      ],
      "TIPO_HORARIO": "Diurno",
      "HORA_INICIO": "7:00:00",
      "HORA_FIN": "22:00:00",
      "TIPO_DIA": [
        "Lunes",
        "Martes",
        "Miercoles",
        "Jueves",
        "Viernes",
        "Sabado"
      ],
      "MUNICIPIO": [
        "MANIZALES",
        "DOSQUEBRADAS",
        "LA VIRGINIA",
        "CHINCHINA",
        "PALESTINA",
        "VILLAMARIA",
        "MARSELLA",
        "SANTA ROSA",
        "RISARALDA",
        "ANSERMA",
        "VITERBO",
        "BELEN DE UMBRIA",
        "NEIRA",
        "MARMATO",
        "PACORA",
        "SUPIA",
        "VICTORIA",
        "NORCASIA",
        "LA DORADA",
        "TAMESIS",
        "JARDIN",
        "ANDES",
        "ABEJORRAL",
        "SANTA BARBARA",
        "LA PINTADA",
        "VALPARAISO",
        "CARAMANTA",
        "NARIÑO",
        "ARGELIA",
        "SONSON",
        "MARULANDA",
        "PENSILVANIA",
        "SAMANA",
        "SALAMINA",
        "AGUADAS",
        "ARANZAZU",
        "QUINCHIA",
        "SAN JOSE",
        "BELALCAZAR",
        "APIA",
        "SANTUARIO",
        "MISTRATO",
        "FILADELFIA",
        "LA MERCED",
        "RIOSUCIO",
        "GUATICA",
        "MARQUETALIA",
        "MANZANARES",
        "BALBOA",
        "LA CELIA",
        "PUEBLO RICO",
        "PEREIRA"
      ],
      "ESTADO": true,
      "MINUTOS": 10
    }];


}
